import Link from "next/link";
import { notFound } from "next/navigation";
import { Building2, ExternalLink, UsersRound } from "lucide-react";
import { chamberLabels, formatDate } from "@cumsevoteaza/parliament-model";
import { getCurrentCompositionData } from "@/lib/composition-data";
import { getPartyPageData } from "@/lib/data";
import { isLocale, type AppLocale } from "@/lib/i18n";
import { selectCurrentPartyState } from "@/lib/public-presentation";
import { EditorialSections } from "../../_components/EditorialSections";
import { EngagementTracker } from "../../_components/EngagementTracker";
import { ShareButton } from "../../_components/ShareButton";
import { ImageWithFallback } from "../../_components/ImageWithFallback";

export default async function PartyPage({params}:{params:Promise<{locale:string;slug:string}>}){
 const {locale:rawLocale,slug}=await params; const locale:AppLocale=isLocale(rawLocale)?rawLocale:"ro"; const [data,currentComposition]=await Promise.all([getPartyPageData(slug),getCurrentCompositionData("official")]); if(!data)notFound();
 const {party,members,legislatureSummaries,groupTotals,votes,formationEvents,governmentParticipations,tribunalSources}=data;
 const logoUrl=legislatureSummaries.flatMap(x=>x.logoUrls)[0];
 const currentLeg=legislatureSummaries[0]?.legislature.id; const current=legislatureSummaries.filter(x=>!currentLeg||x.legislature.id===currentLeg);
 const asOf=new Date().toISOString().slice(0,10); const currentPartyState=selectCurrentPartyState(governmentParticipations,asOf); const government=currentPartyState.participation;
 const deputies=current.find(x=>x.chamber==="deputies"); const senate=current.find(x=>x.chamber==="senate");
 const deputySeatCount=currentComposition.chambers.find(x=>x.chamber==="deputies")?.groups.find(x=>x.party?.id===party.id)?.seats??0;
 const senateSeatCount=currentComposition.chambers.find(x=>x.chamber==="senate")?.groups.find(x=>x.party?.id===party.id)?.seats??0;
 const currentSeatTotal=deputySeatCount+senateSeatCount;
 const recent=groupTotals.flatMap(total=>{const vote=votes.find(v=>v.id===total.voteId);return vote?[{total,vote}]:[]}).sort((a,b)=>b.vote.heldOn.localeCompare(a.vote.heldOn)).slice(0,6);
 const founded=formationEvents.find(x=>x.eventType==="party_founded"); const restored=formationEvents.find(x=>x.eventType==="party_reestablished");
 return <main className="mx-auto grid min-h-[calc(100vh-76px)] max-w-[1440px] grid-cols-1 bg-[#fbfaf6] lg:grid-cols-[minmax(0,1fr)_400px]">
  <div className="min-w-0 px-4 py-7 md:px-8 lg:px-10"><EditorialSections page="party" locale={locale} entityId={slug}/><EngagementTracker entityType="party" entityId={party.id} locale={locale}/>
   <nav className="mb-5 flex flex-wrap items-center justify-between gap-3 text-xs text-[#4b608a]"><span><Link href={`/${locale}`}>{locale==="ro"?"Acasă":"Home"}</Link>　›　{locale==="ro"?"Partide":"Parties"}　›　{party.name}</span><ShareButton href={`/${locale}/parties/${party.slug}`} title={party.name} label={locale==="ro"?"Distribuie această pagină":"Share this page"} copiedLabel={locale==="ro"?"Link copiat":"Link copied"} errorLabel={locale==="ro"?"Copiază manual":"Copy manually"} className="bg-transparent font-semibold text-[#075fc6]"/></nav>
   <header className="flex items-center gap-5 border-b border-slate-300 pb-5"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-md text-xl font-black" style={{background:`${party.color}22`,color:party.color}}><ImageWithFallback src={logoUrl} alt={`${party.shortName} logo`} className="h-full w-full object-contain p-2">{party.shortName}</ImageWithFallback></div><div className="min-w-0"><h1 className="font-serif text-5xl font-semibold leading-[.96] tracking-[-.045em] text-[#050e2c] md:text-[52px] xl:text-[54px]">{party.name}</h1><p className="mt-3 text-sm leading-6 text-[#4b608a]">{locale==="ro"?"Reprezentarea partidului în Parlament, pozițiile la vot și istoricul documentat în surse publice.":"The party's parliamentary representation, voting positions and history documented in public sources."}</p></div></header>
   <section className="mt-5 border border-slate-300 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-serif text-3xl font-semibold text-[#061a47]">{locale==="ro"?"Rolul actual în Parlament":"Current role in Parliament"}</h2><div className="mt-3 flex items-center gap-3"><Building2 size={34} className="text-[#061a47]"/><div><strong className="font-serif text-2xl capitalize text-[#061a47]">{government?alignment(government.alignment,locale):(locale==="ro"?"Reprezentare parlamentară":"Parliamentary representation")}</strong>{government?<p className="text-sm text-[#4b608a]">{government.government.name}</p>:<p className="text-sm text-[#4b608a]">{locale==="ro"?"Fără clasificare guvernamentală verificată":"No verified government classification"}</p>}</div></div></div><span className="text-xs text-[#4b608a]">{locale==="ro"?"Situația la":"As of"} {formatDate(currentComposition.asOf,locale)} · {current[0]?.legislature.label}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><SeatFact label={locale==="ro"?"Camera Deputaților":"Chamber of Deputies"} value={deputySeatCount}/><SeatFact label={locale==="ro"?"Senat":"Senate"} value={senateSeatCount}/></div></section>
   {government?<section className="mt-4 flex items-center justify-between gap-4 border border-[#dae8f7] bg-[#f0f6fc] p-4"><div><strong className="font-serif text-xl text-[#061a47]">{government.government.name}</strong><p className="mt-1 text-sm text-[#4b608a]">{formatDate(government.startsOn,locale)} – {government.endsOn?formatDate(government.endsOn,locale):(locale==="ro"?"prezent":"present")}</p></div><Link href={`/${locale}/compozitii`} className="text-sm font-semibold text-[#075fc6]">{locale==="ro"?"Vezi componența →":"See composition →"}</Link></section>:null}
   <section className="mt-6"><div className="flex items-end justify-between border-b border-slate-300 pb-2"><div><h2 className="font-serif text-3xl font-semibold text-[#061a47]">{locale==="ro"?`Cum a votat recent ${party.shortName}`:`How ${party.shortName} voted recently`}</h2><p className="mt-1 text-sm text-[#4b608a]">{locale==="ro"?"Poziția cumulată a grupurilor în voturile nominale importate.":"Combined group position in imported nominal votes."}</p></div><Link href={`/${locale}/votes?group=${encodeURIComponent(data.groups[0]?.id??"")}`} className="text-sm font-semibold text-[#075fc6]">{locale==="ro"?"Toate voturile →":"All votes →"}</Link></div><div className="divide-y divide-slate-200">{recent.length?recent.map(({total,vote})=><Link key={total.id} href={`/${locale}/votes/${vote.id}`} className="grid gap-2 py-3 text-sm hover:bg-white md:grid-cols-[105px_minmax(0,1fr)_110px_90px]"><span className="text-[#4b608a]">{formatDate(vote.heldOn,locale)}</span><strong className="font-serif text-base text-[#061a47]">{vote.title}</strong><span className="font-semibold text-[#075fc6]">{position(total.for,total.against,total.abstention,locale)}</span><span className="text-[#4b608a]">{agreement(total.for,total.against,total.abstention)}%</span></Link>):<p className="py-4 text-sm text-[#4b608a]">{locale==="ro"?"Nu există încă voturi de grup conectate.":"No connected group votes yet."}</p>}</div></section>
   <section className="mt-6 border border-slate-300 bg-white p-5"><h2 className="font-serif text-2xl font-semibold text-[#061a47]">{locale==="ro"?`Poziționare în legislatura ${current[0]?.legislature.label??"curentă"}`:`Position in the ${current[0]?.legislature.label??"current"} legislature`}</h2><p className="mt-2 text-sm leading-6 text-[#4b608a]">{government?(locale==="ro"?`${party.shortName} are o aliniere de ${alignment(government.alignment,locale)} în ${government.government.name}, conform datelor editoriale aprobate.`:`${party.shortName} is aligned as ${alignment(government.alignment,locale)} in ${government.government.name}, according to approved editorial data.`):(locale==="ro"?"Rolul guvernamental nu are încă o clasificare editorială verificată.":"The government role does not yet have a verified editorial classification.")}</p></section>
  </div>
  <aside className="border-t border-slate-300 bg-white/70 px-6 py-7 lg:border-l lg:border-t-0"><div className="lg:sticky lg:top-24"><section className="border border-slate-300 bg-white p-5"><h2 className="font-serif text-2xl font-semibold text-[#061a47]">{locale==="ro"?"Pe scurt":"At a glance"}</h2><dl className="mt-4 divide-y divide-slate-200 text-sm">{founded?<Fact label={locale==="ro"?"Înființat":"Founded"} value={formatDate(founded.date,locale)}/>:null}{restored?<Fact label={locale==="ro"?"Reînființat":"Re-established"} value={formatDate(restored.date,locale)}/>:null}<Fact label={locale==="ro"?"Prezență":"Presence"} value={[deputies&&chamberLabels[locale].deputies,senate&&chamberLabels[locale].senate].filter(Boolean).join(" și ")||"—"}/><Fact label={locale==="ro"?"Mandate active":"Active seats"} value={String(currentSeatTotal)}/><Fact label={locale==="ro"?"Statut actual":"Current status"} value={government?alignment(government.alignment,locale):(locale==="ro"?"Neclasificat":"Unclassified")}/></dl></section>
   <section className="mt-4 border border-[#dae8f7] bg-[#f0f6fc] p-5"><div className="flex items-center gap-3"><UsersRound className="text-[#061a47]"/><h2 className="font-serif text-xl font-semibold text-[#061a47]">{locale==="ro"?`Parlamentarii ${party.shortName}`:`${party.shortName} members`}</h2></div><p className="mt-2 text-sm text-[#4b608a]">{currentSeatTotal} {locale==="ro"?"mandate active în fotografia curentă. În istoric sunt documentate":"active seats in the current snapshot. The documented history contains"} {members.length} {locale==="ro"?"persoane.":"people."}</p><Link href={`/${locale}/members?group=group-name:${party.shortName.toLowerCase()}`} className="mt-4 block border border-[#9eabc0] bg-white px-3 py-2 text-center text-sm font-semibold text-[#075fc6]">{locale==="ro"?"Vezi parlamentarii →":"See members →"}</Link></section>
   {formationEvents.length?<details className="mt-4 border border-slate-300 bg-white p-4"><summary className="cursor-pointer font-serif text-xl font-semibold text-[#061a47]">{locale==="ro"?"Istoricul partidului":"Party history"}</summary><div className="mt-3 space-y-3">{formationEvents.slice(0,8).map(event=><a key={event.id} href={event.sourceUrl} target={event.sourceUrl?"_blank":undefined} rel="noreferrer" className="block border-l-2 border-slate-300 pl-3 text-sm"><strong>{formatDate(event.date,locale)}</strong><span className="mt-1 block text-[#4b608a]">{locale==="ro"?event.titleRo:event.titleEn}</span></a>)}</div></details>:null}
   {tribunalSources.map(source=><a key={source.id} href={source.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-3 border border-slate-300 bg-white p-4 text-sm font-semibold text-[#075fc6]"><ExternalLink size={19}/>{locale==="ro"?"Registrul oficial al partidului":"Official party registry"}</a>)}
  </div></aside>
 </main>
}
function SeatFact({label,value}:{label:string;value:number}){return <div className="flex items-center gap-4 border-l border-slate-200 px-4"><UsersRound className="text-[#061a47]"/><div><strong className="font-serif text-3xl text-[#061a47]">{value}</strong><p className="text-xs text-[#4b608a]">{label}</p></div></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[105px_1fr] gap-3 py-2"><dt className="text-[#4b608a]">{label}</dt><dd className="font-medium text-[#061a47]">{value}</dd></div>}
function alignment(v:string,l:AppLocale){const ro:Record<string,string>={government:"guvernare",governing_support:"susținere",opposition:"opoziție",mixed:"poziție mixtă",unaffiliated:"neafiliat",unknown:"necunoscut"};return l==="ro"?(ro[v]??v):v.replaceAll("_"," ")}
function position(f:number,a:number,b:number,l:AppLocale){if(f===a&&a===0)return l==="ro"?"Abținere":"Abstain";if(f>=a&&f>=b)return l==="ro"?"Pentru":"For";if(a>=f&&a>=b)return l==="ro"?"Contra":"Against";return l==="ro"?"Abținere":"Abstain"}
function agreement(f:number,a:number,b:number){const all=f+a+b;return all?Math.round(Math.max(f,a,b)/all*100):0}
