import Link from "next/link";
import { notFound } from "next/navigation";
import { Building2, ExternalLink, FileText, MapPin, UserRound } from "lucide-react";
import { chamberLabels, formatDate } from "@cumsevoteaza/parliament-model";
import { getMemberPageData } from "@/lib/data";
import { isLocale, type AppLocale } from "@/lib/i18n";
import { placeForDisplay } from "@/lib/presentation";
import { EditorialSections } from "../../_components/EditorialSections";
import { EngagementTracker } from "../../_components/EngagementTracker";
import { MemberCareerTimeline } from "../../_components/MemberCareerTimeline";

export default async function MemberPage({ params, searchParams }: { params: Promise<{locale:string;slug:string}>; searchParams: Promise<{legislature?:string}> }) {
  const { locale: rawLocale, slug } = await params;
  const { legislature } = await searchParams;
  const locale: AppLocale = isLocale(rawLocale) ? rawLocale : "ro";
  const data = await getMemberPageData(slug, { legislature });
  if (!data) notFound();
  const { member, mandate, group, party, profilePhotoUrl, currentLogoUrl, careerSegments, source, legislatures, selectedLegislature, activity, votes, voteRecords, sponsoredBills } = data;
  const expressed = (activity?.votesFor ?? 0)+(activity?.votesAgainst ?? 0)+(activity?.abstentions ?? 0)+(activity?.presentNotVoting ?? 0);
  const all = expressed+(activity?.absent ?? 0)+(activity?.unknown ?? 0);
  const participation = all ? Math.round(expressed/all*100) : undefined;
  const recent = votes.flatMap(item => { const vote=voteRecords.find(record=>record.id===item.voteId); return vote ? [{item,vote}] : []; }).sort((a,b)=>b.vote.heldOn.localeCompare(a.vote.heldOn)).slice(0,6);
  const shortParty = party?.shortName ?? group?.shortName ?? (locale==="ro"?"Neafiliat":"Unaffiliated");

  return <main className="mx-auto grid min-h-[calc(100vh-76px)] max-w-[1440px] bg-[#fbfaf6] lg:grid-cols-[minmax(0,1fr)_360px]">
    <div className="min-w-0 px-4 py-7 md:px-8 lg:px-10">
      <EditorialSections page="member" locale={locale} entityId={slug}/><EngagementTracker entityType="member" entityId={member.id} locale={locale}/>
      <nav className="mb-5 text-xs text-[#4b608a]"><Link href={`/${locale}`}>{locale==="ro"?"Acasă":"Home"}</Link>　›　<Link href={`/${locale}/members`}>{locale==="ro"?"Parlamentari":"Members"}</Link>　›　{member.displayName}</nav>
      <header className="grid gap-5 border-b border-slate-300 pb-6 sm:grid-cols-[150px_minmax(0,1fr)]">
        <div className="relative h-[188px] w-[150px] overflow-hidden rounded-md border border-slate-300 bg-[#e9eef5]">{profilePhotoUrl?<img src={profilePhotoUrl} alt={member.displayName} className="h-full w-full object-cover"/>:<span className="grid h-full place-items-center font-serif text-4xl font-bold text-[#4b608a]">{initials(member.displayName)}</span>}{currentLogoUrl?<img src={currentLogoUrl} alt="" className="absolute bottom-2 right-2 h-9 w-9 border border-slate-300 bg-white object-contain p-1"/>:null}</div>
        <div className="min-w-0"><h1 className="font-serif text-5xl font-semibold leading-[.96] tracking-[-.045em] text-[#050e2c] md:text-6xl">{member.displayName}</h1><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-[#4b608a]"><Link href={party?`/${locale}/parties/${party.slug}`:"#"} className="flex items-center gap-2 font-semibold text-[#061a47]"><i className="h-3 w-3 rounded-full" style={{background:party?.color??group?.color??"#8996a9"}}/>{shortParty}</Link>{mandate?<span className="flex items-center gap-2"><Building2 size={18}/>{chamberLabels[locale][mandate.chamber]}</span>:null}{mandate?.constituency?<span className="flex items-center gap-2"><MapPin size={18}/>{placeForDisplay(mandate.constituency)}</span>:null}<span className="flex items-center gap-2 font-semibold text-emerald-700"><i className="h-3 w-3 rounded-full bg-emerald-600"/>{mandate?.status??"—"}</span></div><p className="mt-4 max-w-3xl font-serif text-lg leading-7 text-[#4b608a]">{locale==="ro"?`Activitatea verificată a parlamentarului în legislatura ${selectedLegislature?.label??"curentă"}, pe baza voturilor și inițiativelor conectate la sursele oficiale.`:`Verified activity in the ${selectedLegislature?.label??"current"} legislature, based on votes and bills linked to official sources.`}</p></div>
      </header>

      <section className="mt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-serif text-3xl font-semibold text-[#061a47]">{locale==="ro"?"Activitatea în această legislatură":"Activity in this legislature"}</h2><p className="mt-1 text-sm text-[#4b608a]">{locale==="ro"?"Date din voturile nominale și proiectele asociate.":"Data from nominal votes and associated bills."}</p></div><span className="text-xs text-[#4b608a]">{locale==="ro"?"Date la":"Data as of"} {formatDate(activity?.lastActivityOn??new Date().toISOString().slice(0,10),locale)}</span></div><div className="mt-4 grid grid-cols-2 border border-slate-300 bg-white md:grid-cols-4"><ProfileStat icon={<FileText/>} value={expressed} label={locale==="ro"?"voturi exprimate":"votes cast"}/><ProfileStat icon={<UserRound/>} value={participation===undefined?"—":`${participation}%`} label={locale==="ro"?"prezență în date":"attendance in data"}/><ProfileStat icon={<FileText/>} value={activity?.proposals??sponsoredBills.length} label={locale==="ro"?"inițiative legislative":"legislative initiatives"}/><ProfileStat icon={<Building2/>} value={careerSegments.length} label={locale==="ro"?"perioade de mandat":"mandate periods"}/></div></section>

      <section className="mt-7"><div className="flex items-center justify-between border-b border-slate-300 pb-2"><h2 className="font-serif text-2xl font-semibold text-[#061a47]">{locale==="ro"?"Cum a votat recent":"Recent votes"}</h2><Link href={`/${locale}/votes`} className="text-sm font-semibold text-[#075fc6]">{locale==="ro"?"Vezi toate voturile →":"All votes →"}</Link></div><div className="divide-y divide-slate-200">{recent.length?recent.map(({item,vote})=><Link key={item.id} href={`/${locale}/votes/${vote.id}`} className="grid gap-2 py-3 text-sm hover:bg-white md:grid-cols-[105px_minmax(0,1fr)_110px]"><span className="text-[#4b608a]">{formatDate(vote.heldOn,locale)}</span><span><strong className="font-serif text-base text-[#061a47]">{vote.title}</strong></span><span className="font-semibold text-[#075fc6]">{choice(item.choice,locale)}</span></Link>):<p className="py-4 text-sm text-[#4b608a]">{locale==="ro"?"Nu există voturi nominale importate pentru perioada selectată.":"No nominal votes are imported for the selected period."}</p>}</div></section>
      {sponsoredBills.length?<section className="mt-7"><h2 className="border-b border-slate-300 pb-2 font-serif text-2xl font-semibold text-[#061a47]">{locale==="ro"?"Inițiative legislative":"Legislative initiatives"}</h2><div className="divide-y divide-slate-200">{sponsoredBills.slice(0,5).map(bill=><Link key={bill.id} href={`/${locale}/bills/${bill.slug}`} className="block py-3"><strong className="text-[#061a47]">{bill.identifiers.deputies??bill.identifiers.senate??bill.id}</strong><span className="ml-3 text-sm text-[#4b608a]">{bill.title}</span></Link>)}</div></section>:null}
    </div>
    <aside className="border-t border-slate-300 bg-white/70 px-6 py-7 lg:border-l lg:border-t-0"><div className="lg:sticky lg:top-24"><section className="border border-[#dae8f7] bg-[#f0f6fc] p-5"><h2 className="font-serif text-2xl font-semibold text-[#061a47]">{locale==="ro"?"Pe scurt":"At a glance"}</h2><dl className="mt-4 divide-y divide-[#d9e4f0] text-sm"><Fact label={locale==="ro"?"Nume complet":"Full name"} value={member.displayName}/><Fact label={locale==="ro"?"Partid":"Party"} value={shortParty}/><Fact label={locale==="ro"?"Camera":"Chamber"} value={mandate?chamberLabels[locale][mandate.chamber]:"—"}/><Fact label={locale==="ro"?"Circumscripție":"Constituency"} value={placeForDisplay(mandate?.constituency)}/><Fact label={locale==="ro"?"Statut":"Status"} value={mandate?.status??"—"}/><Fact label={locale==="ro"?"Mandat":"Term"} value={selectedLegislature?.label??"—"}/></dl></section><div className="mt-4"><MemberCareerTimeline segments={careerSegments} locale={locale}/></div>{legislatures.length>1?<section className="mt-4 border border-slate-300 bg-white p-4"><h3 className="font-serif text-xl font-semibold text-[#061a47]">{locale==="ro"?"Alte legislaturi":"Other legislatures"}</h3><div className="mt-3 flex flex-wrap gap-2">{legislatures.map(item=><Link key={item.id} href={`/${locale}/members/${member.slug}?legislature=${item.id}`} className={`border px-2 py-1 text-xs ${item.id===selectedLegislature?.id?"bg-[#061a47] text-white":"bg-white text-[#4b608a]"}`}>{item.label}</Link>)}</div></section>:null}{source?.sourceUrl?<a href={source.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-3 border border-slate-300 bg-white p-4 font-semibold text-[#075fc6]"><ExternalLink size={20}/>{locale==="ro"?"Detalii oficiale":"Official details"}</a>:null}</div></aside>
  </main>;
}
function ProfileStat({icon,value,label}:{icon:React.ReactNode;value:string|number;label:string}){return <div className="border-l border-slate-200 p-3 first:border-l-0 md:p-4"><div className="flex items-center gap-2 text-[#061a47] md:gap-3"><span>{icon}</span><strong className="font-serif text-2xl md:text-3xl">{value}</strong></div><p className="mt-1 text-xs text-[#4b608a]">{label}</p></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[105px_1fr] gap-3 py-2"><dt className="text-[#4b608a]">{label}</dt><dd className="font-medium text-[#061a47]">{value}</dd></div>}
function initials(v:string){return v.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function choice(v:string,l:AppLocale){const ro:Record<string,string>={for:"Pentru",against:"Contra",abstention:"Abținere",present_not_voting:"Nu a votat",absent:"Absent"};return l==="ro"?(ro[v]??v):v.replaceAll("_"," ")}
